CREATE DATABASE XWORKZBTM;

CREATE TABLE STUDENT(ID INT,NAME VARCHAR(20),USN BIGINT);

DESC STUDENT;

USE XWORKZBTM;

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUE(1,'KALYAN',123654);

INSERT INTO STUDENT VALUES(2,'DAYANAND',321456);

INSERT INTO STUDENT (ID,NAME)VALUES(3,'DARSHAN');



